pub static OPERACION_INVALIDA: u32 = 101;
pub static DELETE_MAL_FORMATEADO: u32 = 102;
pub static INSERT_MAL_FORMATEADO: u32 = 103;
pub static SELECT_MAL_FORMATEADO: u32 = 104;
pub static UPDATE_MAL_FORMATEADO: u32 = 105;
pub static WHERE_EN_DELETE_MAL_FORMATEADO: u32 = 109;
pub static WHERE_MAL_FORMATEADO: u32 = 110;
pub static ORDER_BY_MAL_FORMATEADO: u32 = 111;
pub static NO_WHERE: u32 = 112;
pub static ARCHIVO_NO_PUDO_SER_ABIERTO: u32 = 201;
pub static ARCHIVO_VACIO: u32 = 202;
pub static ARCHIVO_NO_CONTIENE_COLUMNAS_SOLICITADAS: u32 = 301;
pub static ERROR_RENOMBRADO_ARCHIVO_TEMPORAL: u32 = 401;
pub static ERROR_INTERCAMBIANDO_TEMPORAL_POR_OFICIAL: u32 = 402;
pub static ERROR_OPERACION_INVALIDA_EN_EJECUCCION: u32 = 403;

pub fn print_err(error_code: u32) {
    // TODO print error
    println!("ERROR. Codigo: {}", error_code)
}
